stages:
  - test

variables:
  JMETER_HOME: "$CI_PROJECT_DIR/apache-jmeter-5.6.3"

before_script:
  - chmod +x $CI_PROJECT_DIR/apache-jmeter-5.6.3/bin/jmeter

run_tests:
  stage: test
  script:
    - source /etc/profile   # Carrega o perfil de shell
    - $CI_PROJECT_DIR/apache-jmeter-5.6.3/bin/jmeter -n -t $CI_PROJECT_DIR/apache-jmeter-5.6.3/bin/plans/api.jmx -l results.jtl
    - ls $CI_PROJECT_DIR/apache-jmeter-5.6.3/bin/plans/

  artifacts:
    paths:
    - results.jtl
