name: Run JMeter Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *' # Agendamento diário às 7 da manhã UTC

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Grant execute permission to JMeter
      run: |
        echo "GitHub Workspace: $GITHUB_WORKSPACE"
        chmod +x $GITHUB_WORKSPACE/apache-jmeter-5.6.3/bin/jmeter

    - name: Run JMeter Tests
      run: |
        export JMETER_HOME=$GITHUB_WORKSPACE/apache-jmeter-5.6.3
        export PATH=$JMETER_HOME/bin:$PATH

        currentDateTime=$(date "+%Y%m%d_%H%M%S")
        resultsFile="$GITHUB_WORKSPACE/apache-jmeter-5.6.3/bin/plans/results_${currentDateTime}.jtl"
        reportsDirectory="$GITHUB_WORKSPACE/apache-jmeter-5.6.3/bin/plans/htmlReports_${currentDateTime}"

        jmeter -n -t $JMETER_HOME/bin/plans/api.jmx -l $resultsFile -e -o $reportsDirectory

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: $reportsDirectory/index.html